import {
  Backpack,
  Baby,
  Bath,
  Bike,
  Blocks,
  BookOpen,
  Bot,
  Cake,
  Candy,
  Car,
  Castle,
  Cat,
  Crosshair,
  Crown,
  Dice5,
  Dog,
  Drama,
  Fish,
  Flame,
  Gamepad2,
  Ghost,
  Gift,
  Heart,
  Lamp,
  Microscope,
  Music,
  Palette,
  PartyPopper,
  Pencil,
  Percent,
  Plane,
  Puzzle,
  Rabbit,
  Rocket,
  Shapes,
  Shirt,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Tag,
  Tent,
  ToyBrick,
  TrainFront,
  TreePine,
  Trophy,
  Umbrella,
  Volleyball,
  WandSparkles,
  Waves,
  type LucideIcon,
} from "lucide-react";
import { defaultIcon, type CategoryIconName } from "@/lib/category-config";

export const CATEGORY_ICON_COMPONENTS: Record<CategoryIconName, LucideIcon> = {
  "toy-brick": ToyBrick,
  blocks: Blocks,
  crown: Crown,
  car: Car,
  train: TrainFront,
  plane: Plane,
  rocket: Rocket,
  bike: Bike,
  shapes: Shapes,
  rabbit: Rabbit,
  dog: Dog,
  cat: Cat,
  fish: Fish,
  puzzle: Puzzle,
  dice: Dice5,
  gamepad: Gamepad2,
  palette: Palette,
  pencil: Pencil,
  book: BookOpen,
  microscope: Microscope,
  baby: Baby,
  wand: WandSparkles,
  drama: Drama,
  crosshair: Crosshair,
  music: Music,
  bot: Bot,
  backpack: Backpack,
  lamp: Lamp,
  tree: TreePine,
  tent: Tent,
  castle: Castle,
  volleyball: Volleyball,
  trophy: Trophy,
  waves: Waves,
  umbrella: Umbrella,
  bath: Bath,
  shirt: Shirt,
  candy: Candy,
  cake: Cake,
  party: PartyPopper,
  gift: Gift,
  star: Star,
  heart: Heart,
  sparkles: Sparkles,
  snowflake: Snowflake,
  sun: Sun,
  ghost: Ghost,
  flame: Flame,
  tag: Tag,
  percent: Percent,
};

/** The category's icon (chosen in Admin → Категории), or the default one for its address. */
export function CategoryIcon({ icon, slug, className }: { icon?: CategoryIconName | string; slug?: string; className?: string }) {
  const Icon = CATEGORY_ICON_COMPONENTS[icon as CategoryIconName] ?? CATEGORY_ICON_COMPONENTS[defaultIcon(slug ?? "")];
  return <Icon className={className} strokeWidth={2.2} />;
}
